# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finish_work.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_finish_part(object):
    def setupUi(self, finish_part):
        finish_part.setObjectName("finish_part")
        finish_part.resize(630, 429)
        finish_part.setWindowTitle("Итоги")
        self.label = QtWidgets.QLabel(finish_part)
        self.label.setGeometry(QtCore.QRect(180, 30, 391, 91))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(finish_part)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(finish_part)
        self.label_3.setGeometry(QtCore.QRect(100, 200, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(finish_part)
        self.label_4.setGeometry(QtCore.QRect(100, 260, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_mark = QtWidgets.QLabel(finish_part)
        self.label_mark.setGeometry(QtCore.QRect(290, 270, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(18)
        self.label_mark.setFont(font)
        self.label_mark.setText("")
        self.label_mark.setObjectName("label_mark")
        self.label_mark_2 = QtWidgets.QLabel(finish_part)
        self.label_mark_2.setGeometry(QtCore.QRect(330, 210, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(18)
        self.label_mark_2.setFont(font)
        self.label_mark_2.setObjectName("label_mark_2")
        self.label_right_answer = QtWidgets.QLabel(finish_part)
        self.label_right_answer.setGeometry(QtCore.QRect(430, 150, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(18)
        self.label_right_answer.setFont(font)
        self.label_right_answer.setText("")
        self.label_right_answer.setObjectName("label_right_answer")
        self.pbt_back = QtWidgets.QPushButton(finish_part)
        self.pbt_back.setGeometry(QtCore.QRect(120, 350, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(18)
        self.pbt_back.setFont(font)
        self.pbt_back.setObjectName("pbt_back")
        self.pbt_finish = QtWidgets.QPushButton(finish_part)
        self.pbt_finish.setGeometry(QtCore.QRect(350, 350, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(18)
        self.pbt_finish.setFont(font)
        self.pbt_finish.setObjectName("pbt_finish")

        self.retranslateUi(finish_part)
        QtCore.QMetaObject.connectSlotsByName(finish_part)

    def retranslateUi(self, finish_part):
        _translate = QtCore.QCoreApplication.translate
        finish_part.setWindowTitle(_translate("finish_part", "Dialog"))
        self.label.setText(_translate("finish_part", "Finish"))
        self.label_2.setText(_translate("finish_part", "Вы ответили правильно:"))
        self.label_3.setText(_translate("finish_part", "Всего вопросов:"))
        self.label_4.setText(_translate("finish_part", "Ваша оценка:"))
        self.label_mark_2.setText(_translate("finish_part", "20"))
        self.pbt_back.setText(_translate("finish_part", "Вернуться"))
        self.pbt_finish.setText(_translate("finish_part", "Закончить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    finish_part = QtWidgets.QDialog()
    ui = Ui_finish_part()
    ui.setupUi(finish_part)
    finish_part.show()
    sys.exit(app.exec_())
